Repository kuwala-io/kuwala, pull requests merged in 2021-12, with the labels that each got.

#64 Fix Windows Demo and Installation Issue
  .gitignore
  README.md
  kuwala/README.md
  kuwala/scripts/initialize_windows.sh
  kuwala/scripts/windows/build_all_containers.sh
  kuwala/scripts/windows/build_cli.sh
  kuwala/scripts/windows/build_jupyter_notebook.sh
  kuwala/scripts/windows/build_neo4j.sh
  kuwala/scripts/windows/create_zip_archive.sh
  kuwala/scripts/windows/initialize_all_components.sh
  kuwala/scripts/windows/initialize_core_components.sh
  kuwala/scripts/windows/initialize_git_submodules.sh
  kuwala/scripts/windows/run_cli.sh
  kuwala/scripts/windows/run_jupyter_notebook.sh
  kuwala/scripts/windows/stop_all_containers.sh
Labels: bug, documentation, good first issue

#66 Cleaner Error Message for Incorrect Input in Google-POI
  kuwala/pipelines/google-poi/README.md
  kuwala/pipelines/google-poi/src/app.py
  kuwala/pipelines/google-poi/src/routes/poi_information.py
  kuwala/pipelines/google-poi/src/routes/popularity.py
  kuwala/pipelines/google-poi/src/routes/search.py
Labels: good first issue, pipeline, pipeline/google-poi

#65 :whale: (dockerfile) follow hadolint's best practice
  .github/workflows/google_poi.yml
  .github/workflows/google_poi_pipeline.yml
  .github/workflows/jupyter.yml
  .github/workflows/kuwala_core.yml
  .github/workflows/neo4j.yml
  .github/workflows/neo4j_importer.yml
  .github/workflows/osm_poi.yml
  .github/workflows/population_density.yml
  .gitignore
  kuwala/core/cli/dockerfile
  kuwala/core/jupyter/docker/dockerfile
  kuwala/core/neo4j/docker/dockerfile
  kuwala/core/neo4j/importer/dockerfile
  kuwala/pipelines/google-poi/dockerfile
  kuwala/pipelines/google-poi/src/pipeline/dockerfile
  kuwala/pipelines/osm-poi/dockerfile
  kuwala/pipelines/population-density/dockerfile
Labels: enhancement
