Repository kuwala-io/kuwala, pull requests merged in 2022-02, with the labels that each got.

#79 Add `kuwala/pipelines` to linting GitHub action
  .flake8
  .github/workflows/admin_boundaries.yml
  .github/workflows/database_importer.yml
  .github/workflows/database_transformer.yml
  .github/workflows/google_poi_api.yml
  .github/workflows/google_poi_pipeline.yml
  .github/workflows/google_trends.yml
  .github/workflows/jupyter.yml
  .github/workflows/osm_poi.yml
  .github/workflows/population_density.yml
  .github/workflows/postgres.yml
  Makefile
  README.md
  kuwala/pipelines/osm-poi/src/Processor.py
Labels: CI/CD

#95 Introducing the no-code data platform
  README.md
  docs/images/h3_overview.png
  docs/images/kuwala_collaborative_cycle.png
  docs/images/kuwala_header_github.png
  docs/images/kuwala_title_banner.png
  docs/images/roadmap_button_github.png
  docs/images/slack_join_button_github.png
  docs/images/tool_description_github.png
  docs/images/visual_Github_before_after.png
  kuwala/pipelines/README.md
Labels: documentation

#96 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#97 Contribution guidelines
  CONTRIBUTING.md
  README.md
Labels: documentation

#100 Canvas - Basic Canvas Structure
  kuwala/core/canvas/.gitignore
  kuwala/core/canvas/README.md
  kuwala/core/canvas/package-lock.json
  kuwala/core/canvas/package.json
  kuwala/core/canvas/public/favicon.ico
  kuwala/core/canvas/public/index.html
  kuwala/core/canvas/public/logo192.png
  kuwala/core/canvas/public/logo512.png
  kuwala/core/canvas/public/manifest.json
  kuwala/core/canvas/public/robots.txt
  kuwala/core/canvas/src/components/DataView/index.js
  kuwala/core/canvas/src/components/Header.js
  kuwala/core/canvas/src/components/Nodes/DataSourceNode.js
  kuwala/core/canvas/src/components/Nodes/TransformationNode.js
  kuwala/core/canvas/src/components/Nodes/VisualizationNode.js
  kuwala/core/canvas/src/components/NotificationPanel.js
  kuwala/core/canvas/src/components/Sidebar/NodeHandlers/DataSourceHandler.js
  kuwala/core/canvas/src/components/Sidebar/NodeHandlers/TransformationHandler.js
  kuwala/core/canvas/src/components/Sidebar/NodeHandlers/VisualizationHandler.js
  kuwala/core/canvas/src/components/Sidebar/index.js
  kuwala/core/canvas/src/icons/kuwala_logo.png
  kuwala/core/canvas/src/index.js
  kuwala/core/canvas/src/pages/App.js
  kuwala/core/canvas/src/pages/styles.css
  kuwala/core/canvas/src/reportWebVitals.js
  kuwala/core/canvas/src/setupTests.js
  kuwala/core/canvas/src/store/elementStore.js
  kuwala/core/canvas/tailwind.config.js
Labels: enhancement, core, frontend, canvas
